CREATE TABLE product (
	productID INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL, 
	price DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	description MEDIUMTEXT NOT NULL,
	PRIMARY KEY(productID)
);

